language: c++
sudo: false
addons:
  apt:
    packages:
    - cmake
    - libxrandr-dev
    - libudev-dev
    - libopenal-dev
    - libflac-dev
    - libvorbis-dev
    - libenet-dev
    - libgtk-3-dev
    - g++-7
    - gcc-7
    - clang
    sources:
    - ubuntu-toolchain-r-test
before_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/gcc
  gcc /usr/bin/gcc-7 90; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/g++
  g++ /usr/bin/g++-7 90; fi
- git clone https://github.com/sfml/sfml && cd sfml && mkdir build && cd build &&
  cmake .. -G"$GENERATOR" $CMAKE_FLAGS
- sudo cmake --build . --target install
- cd ../..
script:
- mkdir build && cd build
- cmake .. -DCMAKE_BUILD_TYPE=Release -G"$GENERATOR" $CMAKE_FLAGS
- sudo cmake --build . --target install --config Release
- sudo cmake --build . --target package --config Release
- cd ../ && mkdir deploy
- cp build/$PACKAGE_NAME deploy
matrix:
  fast_finish: true
  include:
  - os: linux
    compiler: gcc
    env:
    - GENERATOR="Unix Makefiles"
    - CMAKE_FLAGS=""
    - PACKAGE_NAME="*.deb"
  - os: linux
    compiler: clang
    env:
    - GENERATOR="Unix Makefiles"
    - CMAKE_FLAGS=""
    - PACKAGE_NAME="*.deb"
  - os: osx
    osx_image: xcode9
    env:
    - GENERATOR="Xcode"
    - CMAKE_FLAGS="-DSFML_BUILD_FRAMEWORKS=TRUE"
    - PACKAGE_NAME="*.dmg"
  - os: osx
    osx_image: xcode9
    env:
    - GENERATOR="Xcode"
    - CMAKE_FLAGS="-DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/iOS.toolchain.cmake"
    - PACKAGE_NAME="*.dmg"
  allow_failures:
  - os: osx
    osx_image: xcode9
    env:
    - GENERATOR="Xcode"
    - CMAKE_FLAGS="-DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/iOS.toolchain.cmake"
    - PACKAGE_NAME="*.dmg"
deploy:
  provider: releases
  api_key:
    secure: T_bh1M_eARmOo1_wvLenUA
   file_glob: true
  file: "deploy/$PACKAGE_NAME"
  overwrite: true
  skip_cleanup: true
  prerelease: true
  on:
   tags: true

    
